### ISSUE TITLE
re-enable `--cache` option

### ISSUE THREAD

**Issue by borkdude** [marcomorain/clojure-lint#3]
since [this issue](https://github.com/borkdude/clj-kondo/issues/285) was fixed, it's now safe to turn it on again

**Comment by marcomorain** [comment]
👍I will need to do a version check at start up to ensure the local version of clj-kondo contains the fix, maybe?

**Comment by borkdude** [comment]
just tell people to upgrade their clj-kondo, I'd say

**Comment by borkdude** [comment]
as a bonus feature for clojure-lint, you could check if people are running the latest and greatest version already. the latest version can be read from here: https://github.com/borkdude/clj-kondo/blob/master/resources/CLJ_KONDO_RELEASED_VERSION

**Comment by borkdude** [comment]
Gave it some more thought and I think the startup check is a good idea. You can print the version of clj-kondo with the `--version` argument.

**Comment by borkdude** [comment]
In case of an error, people will probably try and upgrade both the extension and clj-kondo, post an issue or ask in the Slack channel. So maybe it's not needed, unless you want to :-).

**Comment by borkdude** [comment]
This issue is now fixed with https://github.com/borkdude/clj-kondo/issues/406.
